### ISSUE TITLE
Getting an error saying:  Unable to find element by selector: #signin-link

### ISSUE THREAD

**Issue by noyyhi** [blakek/ms-bing-rewards#12]
Hi, 
Love ur work a lot. I am new here, and I am getting the ERROR: Unable to find element by selector: #signin-link.
May I know how could I solve it?

Best,
Edward

**Comment by blakek** [comment]
Microsoft changed the selectors and I haven't updated this yet.  If I have time tonight, I may look into it and see what's going on.  Also, if you know JavaScript, it should be a really easy fix.  The steps in `src/lib/ms-rewards.js` need to be updated.

**Comment by blakek** [comment]
I've finally pushed up all the changes I've had sitting around for this. It's been re-written and should work with the new sign in pages now.
